### ISSUE TITLE
This is super rad

### ISSUE THREAD

**Issue by whyisjake** [eriktorsner/wp-checksum#1]
Why create this as a composer install, when as a WordPress plugin would be a good fit?

**Comment by eriktorsner** [comment]
Hi,

Thanks for the input. I'm working on a plugin as well, it will be released asap. Releasing as a wp-cli command installed via composer is a combination of convenience (suits my own use case) and a way to get some milage on the backend API from hopefully more "into the gritty details" knowledgeable users.
