### ISSUE TITLE
Add to WP-CLI Package Index?

### ISSUE THREAD

**Issue by davemac** [eriktorsner/wp-checksum#2]
Is it possible to package this a command and add it to the [WP-CLI Package Index](http://wp-cli.org/package-index/)?

Seeing as it as wp-cli command, I feel this would be the preferred way to install it.

**Comment by eriktorsner** [comment]
Absolutely agreee, just haven't got around to it. I'll get the process started later tonight.

**Comment by davemac** [comment]
Cool, [wp scaffold package](https://github.com/wp-cli/scaffold-package-command) might help you with that

**Comment by eriktorsner** [comment]
Sorry about the delay, I've added the pull request to the package index repo now. Should be available as a package soon

**Comment by eriktorsner** [comment]
It's available as a wp-cli package now.
